### ISSUE TITLE
Forbedre figurer og modeller

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#105]
* Forbedre og klargjøre figuren som illustrerer målarkitekturen.
  * Den er fremdeles vanskelig å forstå for noen lesere
* Vurdere om figurene i juridisk kapittel og konsept kapittelet bør modernisere så de ligner mer på figurene i eksempler, kapabilitetsfiguren og målarkitekturfiguren.

**Comment by thomiz** [comment]
Vurdere bytte figur for målarkitektur.
![image](https://user-images.githubusercontent.com/6229665/233363496-c83bbcf8-f487-4d20-800e-0f672a46c8aa.png)

Eventuelt også vise elementer som ikke er en del av målarkitketur:
![image](https://user-images.githubusercontent.com/6229665/233363663-ae21cfb3-efcc-4caa-86c1-0728071e675e.png)

**Comment by thomiz** [comment]
Eksempel på løsning i utprøving:
![image](https://user-images.githubusercontent.com/6229665/233363864-14e188d6-d550-4edd-83cc-87b367086361.png)

**Comment by thomiz** [comment]
Justere figurer i juridisk kapittel og konsept kapittelet.
* Ta bort de konkrete fellestjenesten
* Samme formspråk som selve målarkitekturen

**Comment by thomiz** [comment]
review @geirhan Både juridisk kapittel og konsept vedlegg

**Comment by thomiz** [comment]
* Datadelingstjeneste kan brukes som begrep istedenfor Datadeling i figuren pluss legge til kopien som eget element i figuren
* Begrepsbruk i teksten må også ryddes (løsning vs tjeneste)

**Comment by geirhan** [comment]
Det er litt dårlig kontrast mellom datadelingstjenester og bakgrunnen (kombinasjonen av leverandørtjenester og virksomhet(er). 
![image](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/assets/54140113/c6c9e5df-9609-4048-ad77-ad6b0b867e3c)

**Comment by thomiz** [comment]
Nye figurer på plass, med justerte undertekster.
