### ISSUE TITLE
Dialogmøte vår 2023

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#107]
Arrangere et dialogmøte for målarkitektur og utprøving DHO våren 2023.

**Comment by thorsteffensen** [comment]
Foreslår onsdag den 14. juni kl. 13-15.
Agenda: ....

**Comment by thomiz** [comment]
## Forslag til agenda

1. Justeringer etter 0.8 basert på innspill i innspillsrunden
2. Status på forankring i rådsmodellen, RHF, KS. osv.
3. Innspill til 0.9 versjon
4. Eventuelt

**Comment by thomiz** [comment]
Innkallingen er sendt med denne agenda:
Foreløpig agenda:
1.	Målarkitektur:
a.	Justeringer etter 0.8 basert på innspill i innspillsrunden
b.	Status på forankring i rådsmodellen, RHF, KS. osv.
c.	Innspill til 0.9 versjon
2.	Status utprøving av DHO datadeling
3.	Eventuelt

**Comment by thomiz** [comment]
Utsendelse 2. juni
innspill 12. juni
Møte 14. juni

**Comment by thomiz** [comment]
Gjennomført siste møte 14. juni
