### ISSUE TITLE
Det er usikkerhet knyttet til behovet for PIL fellestjeneste

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#111]
Siden vi ikke ser behovet på kort sikt og alternativer for løsning både juridisk og realisering er udefinert. Vi trenger uansett juridiske betraktninger knyttet til PIL konsepter. Vi trenger dokumenterbare behov fra sektoren på behovet for PIL (ved at det etableres datadeling i mange separate løsninger i mange ulike virksomheter)

**Comment by thomiz** [comment]
Har gjort endringer i sammendraget, krav og anbefalinger og anbefalte tiltak for å synliggjøre usikkerheten knyttet til PIL.
@geirhan review?

**Comment by geirhan** [comment]
Støtter innholdet, det ser bra ut. Har bare delt opp et par setninger, og pyntet litt på en punktliste.

**Comment by thomiz** [comment]
Gått gjennom og lukket
