### ISSUE TITLE
Felles loggetjenester mangler i målarkitekturen

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#112]
Siden vi nevner PIL og tillitstjenester, hvorfor er ikke felles loggetjenester med.
* Kan sees på som endel av tillitstjenestene?

**Comment by thomiz** [comment]
Dette må vi undersøke nærmere, spesielt i forhold til hvilke deler av dette som er regulert i tillitsmodellen og hva som er definert av fellestjenester for dette i målarkitektur fra 2021.

**Comment by geirhan** [comment]
I dokumentet kav og anbefalinger i avsnittet om Informasjonstjenester og prosesser pekes det på at dokumentasjon av tjenstlig behov beskrives i [Målarkitektur for datadeling i helse og omsorgssektoren](https://www.ehelse.no/standardisering/standarder/malarkitektur-for-datadeling-i-helse-og-omsorgssektoren) og er noe som ikke gjentas i målarkitekturen. Spørsmålet da er om det er tilstrekkelig, gitt de diskusjonene som er rundt mer informasjon i sikkerhets-token.

**Comment by thomiz** [comment]
@geirhan Er felles loggtjenester nevnt som en del av tillitstjenestene slik som Målarkitekturen fra 2021 definerer dem?

**Comment by thomiz** [comment]
Dette er beskrevet i målarkitekturen (2021) i kapittel *8.5 Vurdering av felleskomponent for logging og innsyn 
i brukslogg*
