### ISSUE TITLE
Opprette release 0.9.0 til dialoggruppemøte

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#123]
Dialoggruppemøte 14. juni 2023
Arbeidsflyt 0.9.0 versjon

- [x] Oppdatere mkdocs "cover_subtitle:" til "version 0.9.0"
- [x] Version, status og maturity på alle sider til v0.9.0, prerelease og review
- [x] Fyll ut releaseinformasjon for 0.9.0
- [x] Kjøre byggescript
- [x] Oppdatere lenker fra README, videre innspill foregår til currentbuild og master branch

## Rydding

- [x] Oppdatere byggescript slik at version-0.9.0 ikke kan overskrives
- [x] Oppdatere mkdocs "cover_subtitle:" til "currentbuild"

**Comment by Ruthie113** [comment]
Jeg har ikke funnet noen feil. Har bladd raskt gjennom og sjekket en del lenker. Veldig bra jobb @thomiz!
