### ISSUE TITLE
Avansert eksempel med både Bodø og Oslo i eksempelet til 1.0?

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#138]
Flere virksomheter som har svart på høringen har etterlyst at det må bli enklere å se hva målarkitekturen understøtter av samhandlingsmønster og løsningsvalg. Noe av dette kan illustreres ved å beskrive flere eksempler. Det er idag eksempel på hvordan Bodø og Oslo gjør det, i tillegg har vi tatt frem en illustrasjon som viser hvordan PH-gateway i HSØ kan vises i form av målarkitekturen.

Andre relevante eksempler kan være Agder, Østfold, eller Larvik sine utprøvinger

- [x] Beskrive databehandleravtalen mellom Oslo og NHN
- [x] Beskrive datadelingsavtalen mellom Oslo og de andre aktørene
- [x] Fikse figuren i Oslo eksempelet, få med fastlegen og avtalene
~~- [ ] Legge inn illustrasjon av HSØ eksempel~~
~~- [ ] beskrive HSØ eksempel~~
- [x] Bodø eksempel
~~- [ ] Andre eksempel~~

Feature under #148

**Comment by Frsamd** [comment]
Hemit
scenariobaserte eksempler med konkret hvordan dette kan løses både teknisk, avtalemessig og juridisk

**Comment by thomiz** [comment]
Eksempel Bodø lagt inn:  
* **D.2	Bodø og Nordlandssykehuset**

Review @geirhan

**Comment by thomiz** [comment]
Siden HSØ ikke egentlig er igang med utvikling ennå tar vi ikke med eksempel derfra ennå.

**Comment by geirhan** [comment]
Har foreslått noen endringer i dokumentet.
