### ISSUE TITLE
Fremstillingen på e-helse.no fungerer ikke

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#140]
Mange høringsinstanser gir tilbakemelding på struktur og utformingen av målarkitekturen på e-helse.no:

* Manglende nummerering av kapitler og uklar kapittelinndeling på e-helse.no gjør dokumentet uoversiktlig (Helsedirektoratet)

**Comment by thomiz** [comment]
HSØ:
> En generell tilbakemelding er at målarkitekturen fremstår som uoversiktlig og vanskelig 
å sette seg inn i. Dokumentet har mange gjentakelser og mangler oversiktlig 
nummerering/kapitler. For å øke brukervennligheten bør det gjøres strukturelle 
forbedringer, og vurderes om enkelte deler kan kortes ned eller gjøres tilgjengelig i 
Side 6 av 8
vedlegg. Dersom de ulike alternativene til løsning blir presentert tidligere i dokumentet 
vil det være enklere å forholde seg til den øvrige delen av arkitekturen.

**Comment by geirhan** [comment]
Helse Vest:
Saman med ei nettside for høyringa, der navigasjonsmenyen og fleire lenker i teksten ikkje fungerer, har dette i sum gjort høyringsprosessen krevjande. Det har vore vanskeleg å fange essensen i målarkitekturen og dermed få grepet på kva den betyr. Høyringa hadde stått seg betre om ein i tillegg til ei fungerande nettside, hadde samla innhaldet i eit dokument (for eksempel ein pdf) som høyringsinstansane kunne forheldt seg til.

**Comment by thomiz** [comment]
Løsning til release blir å skrive i Word og publisere som PDF.
* Dokumentet eksisterer nå som word, kan redigeres på Teams (Se: FAG DHO/DHO Målarkitektur)
