### ISSUE TITLE
Intern og ekstern datadeling

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#141]
* Til avsnittet "Datadeling og DHO"
> I avsnittet skilles det mellom deling av data internt og på tvers av virksomheter, og det fremgår at det er først når virksomhetene har behov for å utveksle data på tvers av behandlingsnivåer at det juridiske handlingsrommet blir utfordret.  
Det er noe uklart hva som menes her. Regelverket er i utgangspunktet det samme for intern og ekstern deling, men selve tilgjengeliggjøringen kan vanskeliggjøres mellom eksterne virksomheter på grunn av informasjonssikkerhetstiltak.

**Comment by thomiz** [comment]
Fra Oslo om det samme avsnittet:

> avsnittet er egnet til å skape usikkerhet rundt det rettslige handlingsrommet hva gjelder deling av helseopplysninger på tvers av virksomheter. Vi ønsker å poengtere at bestemmelsene som regulerer informasjonsdeling i forbindelse med helsepersonells rett og plikt til å dele relevant og nødvendig informasjon med annet helsepersonell, også gjelder på tvers av 
virksomhetsgrenser og nivåer. Det samme gjelder virksomhetenes plikt for å tilrettelegge for at slik informasjon gjøres tilgjengelig for helsepersonell. Fra vårt ståsted vil det være ønskelig at setningen enten fjernes eller endres slik at den ikke sår tvil om delingsadgangen helseretten åpner for.

**Comment by rvbra** [comment]
Jeg er enig. Setningen kan enten fjernes (enklest) eller bygges ut (forslag kommer).

**Comment by rvbra** [comment]
Hdirs øvrige merknader til jussen er gode og kan også tas direkte inn.

**Comment by thomiz** [comment]
review @thomiz

**Comment by thomiz** [comment]
Det ser bra ut.
