### ISSUE TITLE
Figurteksten i innledningen tyder på at omfanget av målarkitekturen som avgrenses i "Hva er DHO"

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#142]
Figurteksten i innledningen tyder på at omfanget av målarkitekturen som avgrenses i "Hva er DHO"

Egnet for å misforstå.

![Image](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/assets/6229665/143a439e-25c9-4227-bfdc-a73ccc3b13bb)

**Comment by thomiz** [comment]
Også HSØ tolker omfanget å være ganske snevert:
> DHO er i målarkitekturen definert som at “(…) hele eller deler av et behandlingstilbud 
foregår uten fysisk kontakt, der dialog og deling av data mellom pasient/bruker og 
behandler(e) skjer digitalt”. Det er viktig at arbeidet med arkitekturen ikke legger til 
grunn en for snever definisjon av DHO, men omfatter alle typer pasientbehandling 
utenfor helsehjelpsorganisasjoners egne fysiske bygg og behandlingsrom (inkludert 
hjemmesykehus) uavhengig av lokasjon. Slik målarkitekturen viser, omfatter dermed 
DHO en rekke kategorier helsehjelpstjenester og informasjonsbehandlinger som skal 
understøtte eller supplere disse. Når målarkitekturen i hovedsak fokuserer på den delen 
som handler om oppfølging basert på strukturerte data fra pasientens måleapparater, er 
det en fare for at arbeidet mister en helhetlig tilnærming til de kliniske behovene.

**Comment by Frsamd** [comment]
Helseplattformen
I innledningen er det en figur som avgrenser hovedfokuset for arbeidet med målarkitekturen til den delen av DHO som handler om oppfølging basert på data fra pasienten. Vi opplever at spørsmålene direktoratet for e-helse ønsker svar på går utover denne avgrensningen

**Comment by thomiz** [comment]
Vi må synliggjøre at DHO handler om og skal benytte informasjon som kommer fra andre kilder enn den snevre definisjonen av DHO og informasjonstjenestene hvor hoveddelen av informasjonen kommer fra brukerens hjem. Dessuten må det synliggjøres at datadeling skal benyttes for mange andre informasjonstjenester.

**Comment by thomiz** [comment]
Se på endringer i kapittel 2.1. Innledningen som misforstås handler om DHO og egentlig ikke selve målarkitekturen.
Dobbeltsjekk om det er andre steder der vi snevrer inn omfanget unødvendig.

**Comment by thomiz** [comment]
review @geirhan

**Comment by geirhan** [comment]
Lagt til kommentar som peker på at deler av teksten fremstår som et sitat, uten at det er vist hvem det siteres fra.

**Comment by thomiz** [comment]
OK etter endring
