### ISSUE TITLE
Endre prioriteringen av PIL komponent

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#144]
Enkelte virksomheter mener det ikke er behov for PIL komponent men andre mener dette er helt sentralt for å realisere og skalere distribuert datadeling.

**Comment by thomiz** [comment]
Konsolidering i sektoren og leverandørmarkedet fører også til at behovet for PIL, regionalt, er mindre:
"En pragmatisk tilnærming i dagens systemlandskap vil 
kunne gi betydelig effekt uten verken utredning eller etablering av en 
Pasientinformasjonslokalisator. En betydelig andel av relevante og nyttige data vil i 
realiteten kunne hentes fra ett til to kildesystem per pasientforløp, f.eks. fra 
datadelingsløsningen for pasientens bokommune og fra datadelingsløsningen til
pasientens «sørge-for» helseforetak. Rammeavtaler for DHO er inngått og innenfor 
hver helseregion vet vi allerede hvem de aktuelle EPJ-leverandørene er og hvor 
deres kildeløsninger befinner seg. Selv om det teoretisk sett vil være et større antall 
kildesystem og installasjoner i kommunene er det med dagens praksis kun et svært 
fåtalls hovedleverandører og installasjoner som er aktuelle."

**Comment by thomiz** [comment]
PIL kan realiseres innenfor gjeldende rett, mener Oslo kommune.
* Det er utvilsomt konsepter for PIL som kan realiseres innen gjeldende rett, men det er fremdeles litt usikkert om sammenstillingene kan gjennomføres på tvers nasjonalt.

**Comment by thomiz** [comment]
Helse Nord peker på at PIL må realiseres fort og at det bør gjøres med et konsept innenfor gjeldende rett.
> Helse Nord RHF ber Direktoratet for e-Helse iverksette et arbeid for å sikre at etablering 
av PIL-komponent slik beskrevet i Målarkitektur for datadeling samt Målarkitektur for 
datadeling i digital hjemmeoppfølging, kan etableres innenfor gjeldende lover og 
forskrifter. Eventuelle begrensinger må beskrives tydeligere. Helse Nord RHF gjør på 
nåværende tidspunkt ikke nærmere vurdering av behov for fremtidig bruk av PIL-komponenten

**Comment by thomiz** [comment]
NHN påpeker at PIL ikke er nødvendig om alle tar i bruk NHN sin Pasientens prøvesvar løsning.

> Vi er i ferd med å etablere og prøve ut en løsning for deling av pasientens måledata som vil 
løse disse behovene. Og som vil gjøre en PIL unødvendig, dersom sektoren tar i bruk vår 
løsning. Norsk helsenett har allerede, i andre sammenhenger, gitt utrykk for at vi mener at 
løsningen med en PIL ikke vil skalere, og at dette ikke er en god løsning for sektoren.

**Comment by thomiz** [comment]
Hovedkonklusjon, vente og se?
* Trenger erfaringer.

**Comment by geirhan** [comment]
@thomiz Se forslag til endring i siste avsnitt i 1.3

**Comment by thomiz** [comment]
Jeg har gjort noen endringer så du kan gjerne se igjennom igjen @geirhan

**Comment by thomiz** [comment]
review OK
