### ISSUE TITLE
Henvisning til Akson journal

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#146]
Dokumentet henviser til Akson journal, dette er ikke lenger et konsept eller en løsning
som skal løse behov i sektoren og bør fjernes som referanse (Kernel):  

> må sees i sammenheng med de nasjonale tiltakene som for eksempel 
dokumentdeling via Kjernejournal, Akson journal og Helseplattformen som skal 
løse hoveddelen av behovet for samhandling ved å ha en felles journal.".
Akson er i kommunene til en viss grad erstattet av initiativet Felles journalløft, men 
dette initiativet har ikke som ambisjon å etablere en felles journa

**Comment by thomiz** [comment]
Akson journal må fjernes. finnes også endel tekst i vedlegg som må fikses på.

@thomiz legger inn vedlegg i word

**Comment by Ruthie113** [comment]
Rettet henvisninger til å være koblet mot arbeidet i de spesifikke vedleggene løsningsomfang og arkitektur og helhetlig samhandling.

**Comment by Ruthie113** [comment]
@thomiz - Rettet henvisninger til å være koblet mot arbeidet i de spesifikke vedleggene løsningsomfang og arkitektur og helhetlig samhandling. Totalt 3 steder

**Comment by thomiz** [comment]
OK
