### ISSUE TITLE
Omtalen av tillitsrammeverket

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#149]
>Oslo kommune har vært en av kommunene som har deltatt i utprøving av dokumentdeling mellom HSØ 
og forskjellige aktører i kommunen, og gjennom dette også gjort oss noen viktige erfaringer. 
Dokumentdeling (som nylig ble gitt navnet Pasientens journaldokumenter) er implementert i tråd med 
nasjonalt felles tillitsrammeverk som etter lang tids arbeid nå langt på vei representerer konsensus i 
sektoren. Vi tar utgangspunkt i at avtaleverket, samt de strukturene og mekanismene som er etablert 
gjennom dette arbeidet, også kan benyttes for deling av opplysninger i forbindelse med digital 
hjemmeoppfølging. 
Dessverre kan vi ikke se at elementer fra arbeidet med felles tillitsrammeverk og dokumentdeling 
gjenspeiles i dokumentet. Tvert imot er det under overskriften «Tillitstjenester og tjenstlig behov» skrevet 
følgende: «Ved datadeling mellom virksomheter når konsumenten (sluttbruker) gjør oppslag mot 
datatilbyder, må konsumentens tjenstlige behov dokumenteres overfor datatilbyder før data utleveres. 
Det eksisterer ikke mekanismer for å håndtere dette i infrastrukturen i dag, verken i sikkerhetsbilletten 
(må utvides) eller andre tillitsskapende tjenester.»
Dette er direkte feil, og må korrigeres i lys av arbeidet med Tillitsrammeverket.

**Comment by thomiz** [comment]
Beskrivelsen av tillitsrammeverket fra NHN:
[Beskrivelse av tillitsrammeverk.pdf](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/files/12993571/Beskrivelse.av.tillitsrammeverk.pdf)

**Comment by thomiz** [comment]
Endringer i avstnittet om tillitstjenester:  
* Kapittel **5.4.3	Tillitstjenester Tillitsrammeverk og tjenstlig behov**

**Comment by thomiz** [comment]
Endringer i avsnitt om tillitstjenester:  
* Kapittel **5.4.3	Tillitstjenester Tillitsrammeverk og tjenstlig behov**

Review @geirhan @rvbra

**Comment by geirhan** [comment]
Gjort noen forslag til endringer for lesbarhet. 
Savner noe om ansvar eller hvordan det jobbes med teknisk infrastruktur i det siste avsnittet i 5.4.3

**Comment by thomiz** [comment]
Lukkes
