### ISSUE TITLE
Ønsker utvidet omfang av målarkitekturens nedslagsfelt

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#151]
HSØ: 
>  Slik målarkitekturen viser, omfatter dermed 
DHO en rekke kategorier helsehjelpstjenester og informasjonsbehandlinger som skal 
understøtte eller supplere disse. Når målarkitekturen i hovedsak fokuserer på den delen 
som handler om oppfølging basert på strukturerte data fra pasientens måleapparater, er 
det en fare for at arbeidet mister en helhetlig tilnærming til de kliniske behovene. Dette 
understøttes også av behovskartleggingen som ligger til grunn for målarkitekturen. 
Arbeidet baserer seg i stor grad på erfaringer fra pågående initiativer og tidligere 
dokumenterte samhandlingsbehov. Selv om disse erfaringene og initiativene har gitt 
viktig innsikt til arbeidet, kunne et grundigere kartleggingsarbeid gitt et bedre grunnlag 
for å lage målarkitekturen. Helse Sør-Øst RHF savner også at det blir tydeligere hvordan 
deling på tvers av virksomheter og omsorgsnivå skal operasjonaliseres, samt en 
tydeligere kontekst som viser hvem som er konsumenter av data som blir delt. Det er 
vanskelig å få oversikt over hvordan arkitekturvalgene samspiller i en overordnet 
arkitektur. Det bør også være tydelig definert hvilke fellestjenester som skal etableres og 
benyttes for å oppnå datadeling. Siden virksomheter /regioner kan velge ulike løsninger 
må helheten i målarkitekturen beskrives tydeligere.

**Comment by thomiz** [comment]
Dette er et annet produkt en målarkitektur for datadeling. Vi er enige i at helheten i samhandlingen er viktig å belyse og har forsåvidt påpekt at det eksisterer en helhet av samhandlingstjenester som består av kapabiliteter for meldingsutveksling, dokumentutveksling, distribuert datadeling og datadeling med sentrale tjenester. En revidering av dette målbildet kan være på sin plass siden det er noen år gammelt. 

* [Samhandlingsarkitekturer i helse- og omsorgssektoren](https://www.ehelse.no/standardisering/standarder/samhandlingsarkitekturer-i-helse-og-omsorgssektoren)

**Comment by thomiz** [comment]
Dette er i all hovedsak utenfor scope og må svares ut i svar til høringsinstansene.

**Comment by geirhan** [comment]
Støttes

**Comment by thomiz** [comment]
Svar og spørsmål i "svar til høringsinstansene" er omformulert noe, OK
