### ISSUE TITLE
Datadeling og kontekstinformasjon

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#153]
Hvordan sikrer man at tilstrekkelig kontekstinformasjon følger med informasjonen tilgjengeliggjort ved datadeling slik at behandler kan nyttiggjøre seg informasjonen uten å ta for stor klinisk risiko?

Fra HSØ:
> Ansvar for kvalitet og bruk av data
Datadeling som løsning kan by på andre utfordringer enn dokumentdeling. Ved deling av 
journaldokument vil det normalt ligge til grunn en kontekst i form av en 
behandlingssituasjon som gjør at forfatter kan presentere opplysninger som for 
eksempel et prøvesvar i en tilstrekkelig kontekst for en antatt fremtidig konsument, det 
være seg en kollega eller et tilsynspersonell. Ved datadeling vil man kunne miste slike 
sammenhenger. Det er viktig at slike utfordringer synliggjøres og at man er 
oppmerksom på risiko for feil vektlegging av data fordi man ikke kjenner konteksten. 
Feiltolkninger og feil eller mangelfulle innføringer i journal forekommer naturligvis 
også, men risikoen er en annen. Dersom det legges til rette for automatiserte 
vurderinger, for eksempel triagering, varsler eller lignende basert på datadeling, er det 
også viktig å ha tenkt gjennom hvem som har ansvaret for vurderingen, er det behandler 
som har samlet informasjonen, mottaker av data, eller produsent av algoritmen? En slik 
automatisert vurdering vil også innebære at man må forholde seg til bestemmelsene i 
MDR (medisinsk utstyrs forordningen).

**Comment by thomiz** [comment]
* Ikke funksjonelle krav knyttet til dataintegritet, opprinnelse, logging og versjonshåndtering.
* I tillegg til deler av den semantiske spesifikasjonen som skal håndtere hvem som har målt, på hvilken måte og i hvilken sammenheng.
  * Håndtering av provenance, audit event etc.

**Comment by thomiz** [comment]
Forslag foreligger review @Ruthie113

**Comment by Ruthie113** [comment]
@thomiz - Satt inn noen forlag men kun for å være mer presis på hva beskrivelsene peker på.

**Comment by thomiz** [comment]
OK
