### ISSUE TITLE
Kommunisere plan for arbeidet med arkitekturen fremover

### ISSUE THREAD

**Issue by geirhan** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#154]
Flere av høringsinstansene etterlyser en plan for hva som skal se i arbeidet med målarkitekturen fremover.

**Comment by thomiz** [comment]
Målarkitekturen skal videreutvikles, HSØ etterspør dette konkret:
> Det er behov for å utvikle målarkitekturen på enkelte områder, om målarkitekturen skal 
kunne brukes til å styre utviklingen av datadeling i helsesektoren.

**Comment by thomiz** [comment]
Dette ligger utenfor selve målarkitekturen. Tas videre i arbeidet med videre veikart.

 * I programmet (HTO)
 * PDS
 * I linja i det nye Helsedirektoratet

**Comment by thomiz** [comment]
Dette svares ut i svarbrevet til høringsinstansene under punktet:
"Målarkitekturens omfang bør utvides med mer detaljert behovskartlegging og beskrivelse av operasjonalisering av målarkitekturen."
