### ISSUE TITLE
Behandle flere fellestjenester, spesielt knyttet til logg, samtykke og fullmaktsløsninger

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#156]
Angående tillitt:
> For å imøtekomme dette behovet 
burde denne tematikken vært belyst nærmere i målarkitekturen, som hvordan det kan 
legges til rette for bruk av logg. Dersom det i fremtiden legges til rette for at pasienten 
eksplisitt må gi samtykke til deling av data, kan dette redusere behovet for logg. Det bør 
vurderes om samtykke- og fullmaktsløsningen i Helsenorge kan utvides til å omfatte 
muligheten til å gi slik samtykke, men det er viktig å ha en løsning som også ivaretar de 
som ikke er i stand til å gi fullmakt digitalt. Det bør også vurderes om en nasjonal 
sperretjeneste skal etableres og være en del av målarkitekturen

**Comment by geirhan** [comment]
KS:

> Anbefale at tillitsrammeverket i PDS for pasientens journaldokumenter også brukes for
> pasientens måledata. Hva kreves eventuelt?

**Comment by thomiz** [comment]
Disse kapabilitetene er omtalt i målarkitekturen fra 2021 og det må detaljeres i det videre arbeidet med tillitstjenester og andre fellestjenester for logg, samtykke og fullmaktsløsninger.

**Comment by thomiz** [comment]
Dette punktet blir ikke svart ut i denne runden.
