### ISSUE TITLE
Innspill til begreper

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#157]
## Virksomhet, leverandør og regionalt

Fra HSØ:
> Begrepene virksomhet og leverandør bør tydeliggjøres i målarkitekturen, det står 
eksempelvis under formålet med målarkitekturen: Et punkt målarkitekturen skal bidra 
til er: "Legge til rette for kommunikasjon med helse- og omsorgstjenesten, leverandører 
og NHN." I denne sammenheng er det uklart om Sykehuspartner HF (SPHF) anses som 
en leverandør eller inngår i virksomhet (helse- og omsorgstjenesten)? SPHF er 
databehandler, men ikke dataeier og etablerer de nødvendige avtalene for delingen 
internt. Virksomhetsbegrepet er en uklarhet som gjennomgående skaper usikkerhet 
rundt hvilken modell som er gjeldende for Helse Sør-Øst og hvordan regionen kan 
omskrive eget arkitekturvalg til målarkitekturens alternativer. Utfordringen i 
forståelsen her er nok i stor grad relatert til spesialisthelsetjenesten med mange 
virksomheter under "samme" infrastrukturparaply.
Begrepet “regionalt” bør tydeliggjøres da dette ofte relateres til 
spesialisthelsetjenestenes regioner. Innen samhandling kan det være behov for at 
helseforetak, fastleger og kommuner har et regionalt samarbeid om DHO gjennom 
helsefellesskap.

**Comment by Ruthie113** [comment]
Skrevet inn to punkter til diskusjon. Bør tydeliggjøres i 1.0 versjonen

**Comment by thomiz** [comment]
Bør klargjøre begrepene og bruken av disse i målarkitekturen:

* region / regional
* virksomhet
* leverandør

**Comment by thomiz** [comment]
Definisjoner for regional og virksomhet lagt til begrepslisten.

* review @Ruthie113 @geirhan

**Comment by Ruthie113** [comment]
@thomiz Regional datadeling og virksomhet ser greit ut for meg.

**Comment by thomiz** [comment]
Innspill @geirhan ?

**Comment by geirhan** [comment]
Fjernet parenteser rundt datadeling for regional datadeling, og lagt til referanse til definisjonen av behandlingsansvarlig i personvernforordningen, siden det er den pasientjournalloven legger til grunn.

**Comment by thomiz** [comment]
thomiz foreslår for samarbeidsmodellen

**Comment by thomiz** [comment]
Lagt inn kort definisjon.
