### ISSUE TITLE
Oppdatere konseptbeskrivelsen med mer informasjon

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#161]
Bedre beskrivelse av hva konseptene forutsetter og betyr:, husk også bedre eksempler #138 

Fra HSØ:
> Målarkitekturen legger til rette for at aktørene selv kan velge det konseptalternativet 
som passer aktørenes behov best. Likevel refererer målarkitekturen til et anbefalt 
konsept. Som leser kan det være vanskelig å forstå forholdet mellom anbefalt konsept og 
konseptalternativene.

Denne er en del av #148

**Comment by thomiz** [comment]
- [x] Beskrive hovedkonseptet bedre og ny figur for hovedkonseptet (3-i-en figur)
- [ ] Sjekke at teksten i krav og anbefalinger som beskriver målarkitekturen beskriver enkeltkonseptene som ligger i denne
- [ ] Beskrivelsen av målarkitekturen i sammendraget må oppdateres

**Comment by thomiz** [comment]
Sammendrag og teksten i kapittel 5.1 om målarkitekturen er oppdatert.

review @geirhan

**Comment by geirhan** [comment]
Lagt inn noen forslag til endringer for å lette lesbarhet i sammendrag og kapittel 5.1.

**Comment by thomiz** [comment]
Vurdere om "sammenstilt" skal inn i beskrivelsen av regional datadeling med lagring og nasjonal datadleing med lagring (fra juskapittelet.

**Comment by thomiz** [comment]
Gjorde noen oppdateringer for å synkronisere juskapittel med konseptkapittel.
