### ISSUE TITLE
Fastlegen har andre behov enn annet helsepersonell i kommunen

### ISSUE THREAD

**Issue by geirhan** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#162]
Legeforeningen sier:

> Legeforeningens mener det er feil å sette likhetstegn mellom fastlegetjenestens behov og resten av kommunehelsetjenestens behov. Legene har ansvar for diagnostisering og igangsetting av behandling. Det er stor knapphet på ressurser hos fastlegene og i utvikling av forskjellige prosjekter for digital hjemmeoppfølging må det sikres klinikermedvirkning, slik at man ikke tilfører tjenesten ekstra arbeidsoppgaver i forbindelse med datadelingen. I en travel hverdag må data kunne aksesseres ved behov og ikke måtte tas stilling til før det er klinisk nødvendig.

**Comment by thomiz** [comment]
Fører ikke til endringer i målarkitekturen men svares ut i oppsummering av høringssvar.

**Comment by thomiz** [comment]
Er det noen av de samme tilbakemeldingene i svaret fra HSØ?

**Comment by thomiz** [comment]
Review OK
