### ISSUE TITLE
Anbefalte tiltak som eget notat

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#164]
Publisere anbefalte tiltak som et eget notat i forbindelse med publisering av målarkitektur for datadeling i DHO.

* Lenke fra målarkitekturen til anbefalte tiltak notatet.

**Comment by thomiz** [comment]
Notat opprettet

**Comment by thomiz** [comment]
review @geirhan

**Comment by geirhan** [comment]
Savner noen ord om kriteriene for prioritering. Det som sies om skillet mellom 1.3 og 4-6 er bra, men jeg lurer på om det er en prioritering i hver av gruppene, og i så fall hva som styrer den prioriteringen.

**Comment by thomiz** [comment]
Vi sier ikke noe om prioriteringsprosessen i denne runden.
OK etter møtet i dag.
