### ISSUE TITLE
Skrive svarbrev til høringsinstansene

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#165]
Skrive brev til høringsinstansene hvor vi oppsummerer endringene vi planlegger i målarkitekturen basert på innspillene vi har fått i høringen.

Svar på alle issues hvor vi mener vi bør svare:  
[svar-høringsinstanser](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/issues?q=is%3Aissue+label%3Ah%C3%B8ring+label%3Asvar-h%C3%B8ringsinstanser)

Nevne hva vi gjør med andre innspill:  
[endringer til release](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/issues?q=is%3Aissue+label%3Ah%C3%B8ring+label%3A%221.0+release%22)

**Comment by Ruthie113** [comment]
@thomiz Da har jeg laget et forslag til svar til høringsinstansene med utgangspunkt i malen du hadde laget på teamsområde

**Comment by thomiz** [comment]
Veldig bra @Ruthie113 Jeg har lagt inn et par forslag til presiseringer og tillegg, vi må heller ikke glemme å fylle inn punktet om gjeldende rett i tabellen, kan du spørre @rvbra om det?

**Comment by Ruthie113** [comment]
@thomiz - bra forslag til presiseringer. Jeg har godkjent de i svarbrevet og sendt mail til @rvbra

**Comment by thomiz** [comment]
Får du sett på det punktet om PIL @rvbra ?

**Comment by thomiz** [comment]
Avklart i møte i dag
