### ISSUE TITLE
Behovsbildet: Kvalitetssikre behovene mot eksisterende behovsarbeid i programmet

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#19]
Invitere Ruthie
Kan Ruthie få tid til dette inneværende sprint?

**Comment by Ruthie113** [comment]
Nå tror jeg at jeg har fått laget en bruker.
Målet for ettermiddagen er å lese gjennom og eventuelt gi innspill på behovskapittelet i målarkitetkturen før det skal sendes ut i morgen

**Comment by thomiz** [comment]
Kan vi regne denne som gjennomført @Ruthie113

**Comment by thomiz** [comment]
Vi har gjort QA
