### ISSUE TITLE
Forklare prioriteringene og tidsperspektivet for behovene

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#21]
høy/middel/lav - prioritet
kort/mellomlang/lang - sikt

Kan du komme med forslag Ruthie?

**Comment by Ruthie113** [comment]
Skrevet inn forslag, men burde vi hatt noen eksempel knyttet til dette?

**Comment by thomiz** [comment]
Skrev om litt og la det ut så forklaringen var synlig.
Kan du ta [review](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/docs/Behovsbilde.html#behov-sluttbruker-og-funksjonelle-krav) @Ruthie113

**Comment by Ruthie113** [comment]
Lagt inn en justering for å ikke være for bastant. Eller et forslag vi kan få innspill på. Se hva Thor sier ift presentasjonen på fredag også.
