### ISSUE TITLE
Metodekapittel

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#23]
Legge til et kapittel/underkapittel om metode for arbeidet med utvikling av målarkitekturen. Denne må med:
![image](https://user-images.githubusercontent.com/6229665/201839987-891edeae-70fb-42a7-abc7-141705e3cb2a.png)

**Comment by thomiz** [comment]
Målgruppe for målarkitekturen passer inn her

**Comment by thomiz** [comment]
Utkast klart, review @geirhan

**Comment by geirhan** [comment]
Sliter litt med å tolke figuren. Den er ikke helt selvforklarende, og trenger å bli forklart eller forenklet. @thomiz

**Comment by geirhan** [comment]
Har foreslått en del endringer, som jeg mener kan gjøre kapitelet litt mer lettlest. @thomiz

**Comment by thomiz** [comment]
Metode kapittelet er revidert
