### ISSUE TITLE
Test issue fra ikke invitert bruker

### ISSUE THREAD

**Issue by thomasrosenlund** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#31]
Jeg kan finne direktoratet for e-helse og lage issues under repo uten å være medlem av noen e-helse grupper.

**Comment by thomiz** [comment]
FYI @OlavKr1 @hildecaroline 
Mitt alter ego @thomasrosenlund har ikke noen spesiell tilgang til repo. Kun lese tilgang siden repoet i utgangspunktet er åpent . Brukeren er ikke invitert som leser eller skriver så er helt frittstående. Opprettelse av issues går likevel fint.

**Comment by hildecaroline** [comment]
Supert!
