### ISSUE TITLE
Sammendrag

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#48]
Skrive sammendrag av målarkitekturen

**Comment by thomiz** [comment]
Sammendrag tilgjengelig review: 
@Ruthie113 @geirhan @Frsamd

**Comment by Ruthie113** [comment]
Bra! Jeg synes du har fått med hovedpunktene i oppsummeringen så langt Thomas.

**Comment by thomiz** [comment]
Bra sammendrag
@thomiz legger inn lenker til de ulike kapitlene fra sammendraget

**Comment by thomiz** [comment]
DONE: Lenker fra sammendraget

**Comment by thomiz** [comment]
Lage en ny task om oppdatere sammendraget før 0.8 slippes til review
