### ISSUE TITLE
Tillitsanker

### ISSUE THREAD

**Issue by Ruthie113** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#66]
Kan vi se på begrepet tillitsanker versus tillitstjeneste vs tillitsmodell - er det noe her vi bør tydeliggjøre?

**Comment by thomiz** [comment]
Begrepene må ihvertfall inn i begrepslisten.

**Comment by thomiz** [comment]
Dette er tatt inn i begrepslisten i versjon 0.8
