### ISSUE TITLE
Kan vi referere til HOD rapporten om veien videre for NVP og Digi-hjem?

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#67]
Veien videre for Nasjonalt velferdsteknologiprogram og Digi-hjem 2022-2024 er en rapport som ikke er publisert, men som vi lener oss veldig på i forhold til overordnet [målbilde](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/Overordnet-maalbilde/)

Forløpig går lenkene i dokumentet [hit](https://sh.ehelse.no/dihj/_layouts/15/WopiFrame2.aspx?sourcedoc={ef7e38d0-ed5d-4983-9c3c-a73ed4a21b23}) og det er på Direktoratet sin sharepoint.

**Comment by thomiz** [comment]
Vet du om noe sted dette er tilgjengelig for eksterne @Ruthie113 ?

**Comment by thomiz** [comment]
Den rapporten skal ikke publiseres.
@Ruthie113 spør Thor om hvor vi finner digitaliseringstiltakene under tiltak 5
[Tiltak innen DHO frem til 2024](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/Overordnet-maalbilde/#tiltak-innen-dho-frem-til-2024)

**Comment by thomiz** [comment]
Ta bort Resultatmål @thomiz 
Erstatter verdiforslaget med foilen fra foilsettet om formålet og innholdet i målarkitekturen.

**Comment by thomiz** [comment]
Restrukturerte overorndet målbilde så vi ikek er avhengig av dig-hjem rapporten
Review @Ruthie113

**Comment by Ruthie113** [comment]
Forslag foreligger @thomiz

**Comment by thomiz** [comment]
Digi hjem rapporten og henvisningen til denne er slettet
