### ISSUE TITLE
Arbeidsgruppens deltagere - virksomheter?

### ISSUE THREAD

**Issue by Ruthie113** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#69]
Burde det være en liste/ oversikt over hvem som har deltatt i arbeidsgruppen?

**Comment by thomiz** [comment]
Dialoggruppen tenker du på? Altså gruppen med eksterne deltakere. @Ruthie113

**Comment by Ruthie113** [comment]
JA jeg tenker på de eksterne deltagerne fra RHF, kommuner NHN osv. Selv om det ikke skal stå navn som viser det virksomhetene som har deltatt. Vi praktiserer vel litt ulikt i Direktoratet og i rapporter som publiserers, men noe vi kan vurdere. De hadde denne i målarkitektur for datadeling som vi bygger på 
![image](https://user-images.githubusercontent.com/118193048/224629606-d316ab3a-cc2b-4a3c-aba4-c3b588ee2efe.png)

**Comment by thomiz** [comment]
review av siden @Ruthie113 @thorsteffensen

**Comment by thomiz** [comment]
OK fra Thor og Ruthie
