### ISSUE TITLE
Ansvarsfordeling

### ISSUE THREAD

**Issue by thorsteffensen** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#76]
Både NHN og KS mener at det er viktig å få med noe om ansvarsfordeling i målarkitekturen. Vet ikke helt hva som menes, men tolker det som at det menes en oversikt over hvem som har ansvar for hva (rollefordeling) i en realisering av konseptene? Det bør avklares hva som menes og det må vurderes om dokumentet skal oppdateres med en slik oversikt.

**Comment by thomiz** [comment]
@thorsteffensen Det kjedelige svaret er vel at målarkitekturen ikke egentlig tar stilling til hvem som har ansvaret for utviklingen av komponentene/tjenestene, men at vi ser at noen kapabiliteter bør realiseres som fellestjenester.

**Comment by thorsteffensen** [comment]
kan du sjekke med Erik H, han var også i møtet med NHN der dette spesielt ble nevnt.

**Comment by thomiz** [comment]
Ansvar for utvikling og realisering av målarkitektur avklares og bestemmes andre steder. Målarkitekturen inneholder ikke disse avklaringene, kan eventuelt nevnes [her](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/innledning/#problemstillinger-som-ikke-behandles)

Dataansvar og databehandleransvar i forhold til realiseringskonseptene kan målarkitekturen klargjøre. Det har også vært endel av diskusjonen med partene. Det er antakelig mest fornuftig å omtale i forbindelse med vurdering av [realiseringskonseptene](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/Konsepter-realisering/)? 

Eventuelt som en oppsummering knyttet til [juridiske vurderinger](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/Juridiske-rammebetingelser/)?

**Comment by thomiz** [comment]
Det oppsummeres nå hva dataansvar og databehandleransvar betyr i juridisk kapittel
