### ISSUE TITLE
Innledning - Bruk av datadeling - generelt vs DHO spesifikt

### ISSUE THREAD

**Issue by thorsteffensen** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#77]
Konseptfiguren viser deling av data mellom virksomheter. Få frem om konseptet er generelt eller spesielt for DHO. Er dette et konsept som like gjerne kunne gjelde deling av data mellom ulike virksomheters EPJ? 
Viktig å få frem hva som er generelt, og hva som er DHO (måledata) spesifikt - også i de juridiske vurderingene.

**Comment by thomiz** [comment]
Dette er en balansegang. Vurderingene som gjøres handler om anvendelse av datadeling innenfor DHO området, med de forutsetninger og behov vi har identifisert der. Mønsteret kan gjenbrukes for mange tilfeller av datadeling mellom virksomheter, men andre brukerhistorier kan føre til andre krav, for eksempel der det identifiseres større behov for nasjonal samhandling hvor behovet for å sammenstille data på tvers av mange virksomheter understøtter behovet på en bedre måte, slik vurderingen var for pasientens prøvesvar for eksempel.

**Comment by thomiz** [comment]
Vi lukker denne med begrunnelsen over, du må gjerne kommentere @thorsteffensen
