### ISSUE TITLE
Det var denne branchen vi erstattet med en ny?

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#83]
@geirhan 
[Omstrukturering av behovsbilde](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/tree/Omstrukturering-av-behovsbilde)

Kan vi da slette den?

**Comment by geirhan** [comment]
Og da er den slettet.

**Comment by thomiz** [comment]
Perfekt!
