### ISSUE TITLE
Klinisk begrunnet forbedring av spesialistbehandling for Kols ved innsyn i historiske måledata

### ISSUE THREAD

**Issue by Per-Henning** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#84]
Datadeling relatert til digital hjemmeoppfølging er en svært kompleks og ressurskrevende utfordring. I alt dette er det viktig å løse utfordringen helhetlig, men det er minst like viktig å være trygg på at en så omfattende løsning bygger på helt reelle og betydningsfulle kliniske behov som er viktige nok til å forsvare ressursbruken – og som leder til mer bærekraftige helsetjenester. I dette ligger det ikke en påstand om at DHO ikke er viktig, eller at datadeling i DHO ikke er nødvendig – men det ligger et åpent spørsmål om vi virkelig har forstått informasjonsbehovene godt nok før vi dykker inn i løsningsmodellenes detaljer.

Det er flott at målarkitekturen tar inn et helt konkret eksempel på DHO og datadeling. I eksempelet oppfattes mål om å hjelpe pasienten til å være mest mulig selvhjulpen, til å holde behandlingen på lavest mulig nivå og til at all helsehjelp skjer på et godt informert grunnlag. Dette er gode mål. Likevel synes det å være dels tatt for gitt at mer informasjonstilgang alltid er et gode uten å begrunne dette i hvordan informasjonen bidrar til bedre helsehjelp. 
Både generelt og i eksempelet med Kols mangler en forklaring til _hvordan_ tilgang til historiske målinger av blodtrykk, oksygenmetning, puls og vekt fra primærhelsetjenesten gjør spesialistbehandlingen signifikant bedre enn hva den er uten tilgang til slike data. 

Det viktigste kliniske resonnementet mangler altså, og det er viktig å få på plass fordi dette sier noe om hvordan man i ettertid kan avgjøre om datadelingen gir ønsket klinisk effekt eller ikke. Dette bør være mest mulig konkret, gjerne i form av typiske og tallfestede former for over/under/feilbehandling som gjøres mot denne pasientgruppen av spesialist som konsekvens av mangel på historiske måledata - slik at vi vet hva vi skal forvente mindre av framover. Uten slike forventninger har vi jo i realiteten ikke noe mål, bare forhåpninger…

Hvis det virkelig er slik at historisk tilbakeblikk på de fire måleparameterne er svært viktig for spesialistens behandling på sykehuset så bør vi også lete etter hvordan dette behovet enklest og raskest kan løses på kort sikt. Kanskje kan oversendelse av et sammendrag av målingene gjøres som en del av henvisningen f.eks, og på den måten dekke 90% av spesialistens behov med 1% av innsatsen versus etableringen av nasjonal datadelingsinfrastruktur…?

Kunne man f.eks tydeliggjort behovsbildet ved å bruke KOLS-eksempelet skissert i tre ulike scenarier – gjerne personas-baserte fortellinger i tre varianter?
a)	Der spesialistbehandlingen skjer uten spesialistens kjennskap til historiske måledata fra primærhelsetjenestens eventuelle DHO (as-is)
b)	Der spesialistbehandlingen skjer med innsyn i historiske måledata fra kommunens DHO (to-be)
c)	Der spesialistbehandlingen skjer med innsyn i mottatt kopi av aggregerte måledata fra kommunens DHO (could-be?) 
Hva skiller det typiske kliniske utfallet, pasientopplevelsen og ressursbruken i fortelling a, b og c og hvorfor?

**Comment by thomiz** [comment]
Takk for gode innspill til målarkitekturen @Per-Henning !

Jeg oppfatter at kommentaren går på to hovedspørsmål: 

* Hva er den kliniske nytten av informasjonen som skal utveksles?
* Er det andre former for samhandling som kan etableres raskere og billigere og gi den samme nytten?

**Comment by thomiz** [comment]
Takk for godt innspill @Per-Henning 

Vi jobber nå med noen konkrete eksempel som vi kan legge inn i målarkitekturen som kan beskrive klinisk nytte. Dette vil være eksempel som viser beslutning om behandling/oppfølging tatt av helsepersonell basert på at de har fått tilgang til rapporterte data fra pasient. Viser for øvrig til referanseliste. Samtidig vil vi fortsette å samle resultater og erfaringer fra tjenesten gjennom samarbeidet i Nasjonalt velferdsteknologiprogram og kontakt med andre Helseforetak for å få et bedre bilde av de effektene som DHO kan gi for innbygger, tjenesten og helsepersonell.  

Vi ser også at det er noen mangler i forhold til dokumentasjonen av hvorfor nettopp datadeling er valgt som samhandlingsform for de informasjonsbehovene som er mest sentrale for DHO området. Vi ønsker å tydeliggjøre dette valget ytterligere i neste versjon av målarkitekturen. Dette valget vil blir drøftet både i behovsdelen og i forhold til dokumentasjon av de viktigste arkitekturvalgene og grunnlaget for arkitekturvalgene.

**Comment by thomiz** [comment]
Disse er svart ut i behovskapittelet med begrunnelse for valg av datadeling som samhandlingsform og nyttevurderinger fra klinikere knyttet til behov for informasjon.
