### ISSUE TITLE
Innspill til vedlegg anbefalte tiltak

### ISSUE THREAD

**Issue by bjarteak** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#86]
Det står at det er en prioritert liste av tiltak, så da antar jeg at 1 er viktigst og videre nedover til 6. Det jeg savner er en beskrivelse av hvilke tiltak er nødvendige for å realisere en løsning for DHO (minimumsløsning). Er alle 6 nødvendige, eller for eksempel 1-3? Er ikke sikkert det hører hjemme i målarkitekturen som skal beskrive målbildet på et gitt tidspunkt, men kunne uansett vært fint med en beskrivelse av hva som er absolutt nødvendig, og hva som er mulig videreutvikling.

**Comment by thomiz** [comment]
Ny tekst for nødvendige tiltak
* Håndtert i [commit](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/commit/1bcfae3315a5da9366982e31ddc56bde27d275d0)

**Comment by thomiz** [comment]
* Kommentert av @geirhan  
* Justert basert på kommentarer
