### ISSUE TITLE
brukerhistorie 2 

### ISSUE THREAD

**Issue by hildecaroline** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#87]
Som helsepersonell har jeg behov for å samarbeide med pasient og annet helsepersonell om dokumentasjon av felles sannhet for informasjon som behandlings- og egenbehandlingsplaner, målinger og legemiddellister, der mange bidrar med en delmengde av informasjonen og kompetanse slik at beslutninger tas med utgangspunkt i oppdater tinfromasjon.
**Forslag endring:**
Som helsepersonell har jeg behov for å samarbeide med pasient og annet helsepersonell om pasientens helseopplysninger. Eksempelvis, lese og oppdatere informasjon i behandlings- og egenbehandlingsplaner, målinger og legemiddellister, slik at beslutninger tas med utgangspunkt i oppdatert informasjon.

**Comment by xivind** [comment]
@thomiz det mangler vel en ".. slik at.." på brukerhistorie 1 og 3 også ser det ut som.

**Comment by Ruthie113** [comment]
Det kommer oppdatert forslag, men det ligger foreløpig i word under FAG-DHO målarkitektur på Teams. Til diskusjon i neste interne arbeidsmøte?

**Comment by thomiz** [comment]
@xivind ordlyden er litt forskjellig men brukerhistorie 1 har begrunnelse: "for å yte helsehjelp til pasient på en effektiv måte" og 2 har tilsvarende begrunnelse "for å mestre og ivareta egen helse".

**Comment by thomiz** [comment]
Nytt forslag:

> For en noen helseopplysninger har jeg som helsepersonell behov for en felles autoritativ kilde til informasjon slik at jeg kan samarbeide med pasient og annet helsepersonell om oppdatering av en felles autoritativ kilde. Eksempler er behandlings- og egenbehandlingsplaner, legemiddellister og kritisk informasjon hvor det er behov for at alle kan oppdatere og lese felles autoritativ kilde.

**Comment by thomiz** [comment]
Oppdatere og dele kan benyttes som begreper i brukerhistorien.

**Comment by Ruthie113** [comment]
Som helsepersonell har jeg behov for å se, oppdatere og dele utvalgt informasjon, som behandlings- og egenbehandlingsplaner, legemiddellister, kritisk informasjon, slik at jeg kan samarbeide med pasient og helsepersonell om oppdatering av en felles autoritativ kilde. 

Var det ca dette som ble konklusjonen fra sist møte?

**Comment by thomiz** [comment]
Som helsepersonell har jeg behov for å endre og dele utvalgt informasjon, slik at jeg kan samarbeide med pasient og helsepersonell om oppdatering av en felles autoritativ kilde. Eksempler på slik informasjon er behandlings- og egenbehandlingsplaner, legemiddellister og kritisk informasjon.

**Comment by thomiz** [comment]
Den er OK
