### ISSUE TITLE
Informasjonstjenester 

### ISSUE THREAD

**Issue by hildecaroline** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#88]
Hva med å enten linke til en oversikt over informasjonstjenestene eller legge tabell med mapping til informasjonstjenester som vedlegg? Mindre leservennlig med referanse-nr som mange ikke har noe forhold til.

**Comment by thomiz** [comment]
Vi legger inn en lenke til informasjonstjenestene og definisjonen av dem på det angitte stedet i dokumentet

**Comment by thomiz** [comment]
Lukket etter [commit](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/commit/3e79b881b094d8128529f8e7ce0290645ddb2cd5)
