### ISSUE TITLE
arkitekturprinsipp 1

### ISSUE THREAD

**Issue by hildecaroline** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#89]
En liten kommentar til det å ta utgangspunkt i brukerbehov. Vi nevner ikke noe om det er realistisk å få fremstilt informasjonen på en brukervennlig måte hos feks fastleger. Jeg vet det er utenfor scope, men uten den delen er det vanskelig å vite om det blir en god løsning for brukerne. Kun refleksjon.

**Comment by thomiz** [comment]
Kan vi legge lenke til brukerbehovene (kapitelet i detaljert behovsbilde) fra arkitekturprinsippene.

**Comment by thomiz** [comment]
Fikset med [lenke](https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/commit/b07748605735225d41d2b8d0984a156657bbab7c)
