### ISSUE TITLE
Forenkle konseptene visuelt og fokusere på hovedpoenger

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#9]
* Forenkle løsningskonseptene visuelt slik at de kommuniserer bedre.
* Fokusere den visuelle fremstillingen på hovedpoengene som skal kommuniseres om hvert enkelt konsept.

**Comment by thomiz** [comment]
Tydelig tilbakemelding på at eksisterende konseptfigurer (med konkrete tjenester i gult) ikke kommuniserer godt nok. Vi har nye versjoner som vi tar i bruk.
* Teksten rundt konseptene kan også forbedres

**Comment by thomiz** [comment]
Sende en epost til kommunikasjon om forklaring av hva DHO er i en enkel figur
* Forløpsfigurene fra Oslo/larvik
* Definisjonen av DHO

**Comment by thomiz** [comment]
@Ruthie113 Ser på teamsområdet til spredningsprosjektene etter illustrasjoner som kan fungere til å vise hva DHO er/handler om
@thomiz sender mail til Tor med utganspunkt i overordnet figur for datadeling DHO og definisjon om hvordan vi kan kommunisere dette

**Comment by thomiz** [comment]
Ny tekst som forklarer omfang og nye figur som viser hva DHO er for noe i innledningen (index.md)

**Comment by thomiz** [comment]
Gjort omstrukturering slik at overordnet vurdering foreligger for alle konseptene og forbedrer ordlyd slik at den skal være mer konsistent.
Dessuten kommer anbefalt konsept (fleksibelt) først.

**Comment by thomiz** [comment]
Trenger review @Ruthie113 @geirhan

**Comment by thomiz** [comment]
Beskrive hvor er det fleksibilitet og hvilke føringer målarkitekturen gir

* Målarkitekturen er teknisk i forhold til digital samhandling mellom aktører
  * Må ha en fleksibilitet for å understøtte dagens og fremtidens behov
  * Konteksten og prosessene som eksempler på hva samhandlingen skal løse

**Comment by Ruthie113** [comment]
Lagt inn lenke til animasjonsfilm. 
Jeg finner ingen bedre illustrasjoner enn den vi har fra SIV/Larvik
Evt kan vi lenke til aktuell temaside med øvrige eksempler - evt legge i referanseliste

**Comment by thomiz** [comment]
@geirhan review?

**Comment by thomiz** [comment]
Fått review muntlig
