### ISSUE TITLE
Begreper: Felleskomponent vs fellestjeneste

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#91]
Det ser ut som disse begrepene benyttes litt om hverandre i dokumentet. Bare ~~Fellestjeneste~~Felleskomponent er omtalt i [Begreper](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/version-0.8/vedlegg/Begreper/)

**Comment by geirhan** [comment]
Prøver meg med en liten justering av definisjonen for felleskomponent: Defineres som **avgrensede deler av en IT-løsning**, som kan gjenbrukes i flere IT-løsninger for å dekke felles behov. De kan brukes på tvers av e-helseløsninger, virksomheter og forvaltningsnivå, og kan enten være frivillig eller påkrevd å bruke.
Liker ikke definisjoner, som bruker deler av ordet som skal defineres i selve definisjonen.

**Comment by thomiz** [comment]
Se også igjennom dokumentet om vi bruker begrepene riktig.

**Comment by geirhan** [comment]
Har gått igjennom alle kapitelene, og skal ha justert bruken av felleskomponent, slik at det stemmer med definisjonen.

**Comment by thomiz** [comment]
Vi kan vel ikke endre tekst inne i et sitat? (fra [Anbefalte-tiltak](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/vedlegg/Anbefalte-tiltak/#etablering-av-pil))

~~~
!!! quote "Pasientinformasjonslokalisator"

    Det er i en rekke situasjoner tilknyttet datadeling behov for å kunne fremskaffe en oversikt over hvem som har en pasientjournal for en gitt pasient.
    ...
    Et slikt register bør etableres som en fellestjeneste hvor det fremgår hvem som har helseopplysninger om en gitt pasient. Vi har valgt å kalle denne fellestjenesten for pasientinformasjonslokalisator, forkortet til PIL.
~~~

**Comment by thomiz** [comment]
Endringene er godtatt og lagt inn i master
