### ISSUE TITLE
Begreper: konsekvent bruk av begreper

### ISSUE THREAD

**Issue by xivind** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#93]
Noen begreper brukes litt om hverandre. Kan muligens være bra å redegjøre for evt. synonymer innledningsvis, og så holde seg til kun ett begrep. Det vil si, er vel strengt tatt termer, men dere skjønner sikkert hvor jeg vil :) 

- [x] Evner vs kapabiliteter
- [x] DHO vs digital hjemmeoppfølging
- [x] Utprøving og spredningsaktiviteter vs Utprøvings- og spredningsaktiviteter
- [x] velferdsteknologisk knutepunkt (VKP) med stor eller liten V
- [x] ..

Denne issue henger muligens sammen med https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging/issues/91

**Comment by Ruthie113** [comment]
Gått igjennom og beskrevet endringer underveis med forsøk på å være mer kknsistent

**Comment by thomiz** [comment]
Bra, jeg har gjort review.
