### ISSUE TITLE
Navngivning og omfang av kapittel "Krav og anbefalinger"

### ISSUE THREAD

**Issue by xivind** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#94]
Et par tanker tanker om dette kapittelet:

- Tittelen er muligens noe tvetydig, særlig begrepet "anbefalinger". Det kan tolkes som anbefaling fra arbeidet med målarkitektur. Men det kan også tolkes som anbefalinger for dho, jf. at anbefalinger er et normeringsnivå. Kan nok enkelt løses ved å ha en noe mer utfyllende overskrift
- Det er ikke helt tydelig akkurat hvor kravene ligger og hvor anbefalingene ligger. Kanskje dette kunne vært formulert mer eksplisitt, evt. med underoverskrifter, slik at man lett finner igjen innholdet om hovedoverskriften bærer bud om. 
- Kapittelet er ganske omfangsrikt. Det er nok kanskje gode grunner for å ha alt samlet, men det kunne kanskje økt lesbarheten å splittet det opp, slik at det blir nærmere omfanget til f. eks. behovskap?

**Comment by thomiz** [comment]
Dette er tydeliggjort i forbindelse med dokumentasjon av arkitekturvalgene som er kommet i den nye versjonen av dokumentet.
Se også #97
