### ISSUE TITLE
Utvidelse av informasjonstjeneste - metamodell

### ISSUE THREAD

**Issue by xivind** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#95]
I behovskapittelet gjøres det to steder rede for viktige skiller, henholdsvis:

- "Vi skiller i det videre arbeidet mellom informasjonsbehov og funksjonelle krav."
- "I arbeidet med å kartlegge informasjonsbehov skiller vi mellom informasjonsressurser og informasjonstjenester som må etableres for å understøtte informasjonsbehovet"

Etter hva jeg kan forstå vil modellen i vedlegget om metamodell være veldig nyttig for å forklare disse skillene. I så fall må den vel utvides med informasjonsbehov og funksjonelle krav. Jeg tror dette kunne vært til hjelp for leseren. Det er jo ganske viktig at man forstår hva disse skiller betyr i praksis for å følge med på resonnementene som følger. Det kunne med fordel også vært lenket til denne modellen, tror jeg, så den blir lettere tilgjengelig når man sitter og leser behovskap. 

Her er modellen det gjelder:
![image](https://user-images.githubusercontent.com/8987107/224704840-6cbbe0c4-e356-4e9e-a85c-79c687c4d3a2.png)

**Comment by thomiz** [comment]
Det første poenget er godt beskrevet i den overordnede, metamodellen slik jeg tolker det.
> I arbeidet med å kartlegge informasjonsbehov skiller vi mellom informasjonsressurser og informasjonstjenester som må etableres for å understøtte informasjonsbehovet

Funksjonelle krav er ikke nevnt verken i den overordnede eller den detaljerte modellen. Hvis vi justerer den detaljerte modellen kan det kanskje se slik ut @xivind?  

![image](https://user-images.githubusercontent.com/6229665/225289515-51fe097e-4acf-456a-bd43-efe566b759fd.png)

**Comment by xivind** [comment]
Helt enig @thomiz , det første skillet (informasjonsressurs og informasjonstjeneste) er tydelig beskrevet i modellen allerede. Når det gjelder det andre skillet (funksjonelle krav og informasjonsbehov) synes jeg forslaget ditt løser det på en god og dekkende måte. Jeg liker løsningen med å aggregere både informasjonsbehov og funksjonelle krav opp i brukerbehov, samtidig som det nå kommer tydelig frem at både informasjonsbehov og funksjonelle krav er knyttet til use-casen.

**Comment by xivind** [comment]
Var ikke meningen å stenge den :) Det får du bestemme, men ditt endringsforslag svarer hvert fall ut min kommentar.

**Comment by thomiz** [comment]
Denne skal inn i 0.9 versjon, men er ikke å anse som bugfix.

**Comment by thomiz** [comment]
Oppdatert figur og litt tekst, inkludert definisjonen i begreper
