### ISSUE TITLE
Begrepet "Tjeneste" har feil definisjon

### ISSUE THREAD

**Issue by thomiz** [Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging#96]
[Begrepet](https://direktoratet-for-e-helse.github.io/Malarkitektur-digital-hjemmeoppfolging/currentbuild/vedlegg/Begreper/) benyttes i hovedsak i forhold til å beskrive "helsetjeneste". Bare et fåtall ganger benyttes "tjeneste" som et begrep for å omtale en generell (IT-)tjeneste eller om automatisert tjeneste for å understøtte samhandling/databehandling. Det er heller ikke en teknisk komponent, men en definert tjeneste som tilbyr kjent funksjonalitet til omverdenen. Tjenesten realiseres av applikasjonskomponenter, funksjoner og prosesser.

Kan kanskje ta utgangspunkt i [datakatalogen](https://data.norge.no/concepts?q=tjeneste) men vi har kanskje også andre definisjoner som innskrenker til helseområdet fra arbeidet med helhetlig samhandling?

**Comment by Ruthie113** [comment]
I datakatalogen er det ingen definisjoner sett fra Helsetjenesten. 
Definisjonen av Tjeneste er i PDS steg 2: En IKT-tjeneste som formidler informasjon knyttet til et bestemt tema. Kan benyttes i mange ulike arbeidsprosesser, og av ulike profesjoner. Tjenester kan leveres som del av samhandlingsløsninger. Begrepet må ikke forveksles med helsetjenester.
Vi bruke denne definisjonen (hvis det er riktig beskrivelse) i begrepslista eller så kan vi skrive IT-tjeneste i teksten uten å definere det i begrepslista og på den måten skille en helsetjeneste fra en IT-tjeneste? 
Tjenestebegrepet er generelt krevende da det bruke si så mange ulike sammenhenger

**Comment by thomiz** [comment]
@Ruthie113 sjekker at IT-tjeneste ikke er med i deifnisjonen, evnt justerer

**Comment by Ruthie113** [comment]
Fjernet fra begrepsliste

**Comment by thomiz** [comment]
Det ble dessverre litt feil. Det var bare biten om IKT tjeneste som skulle bort. Teksten referert den 15. mars var dessverre allerede fikset på så vi tar det inn igjen.
